version: '3.4'

services:

  seq:
    image: datalust/seq:latest

  sqldata:
    image: mcr.microsoft.com/mssql/server:2017-latest 

  nosqldata:
    image: mongo

  mongo-express:
    image: mongo-express:latest
    depends_on:
      - nosqldata

  basketdata:
    image: redis:alpine
  
  redis-commander:
    image: rediscommander/redis-commander:latest
    depends_on:
      - basketdata

  rabbitmq:
    image: rabbitmq:3-management-alpine

  identity-api:
    image: ${REGISTRY:-eshop}/identity.api:${BRANCH_NAME:-master}
    build:
      context: .
      dockerfile: Services/Identity/Identity.API/Dockerfile
    depends_on:
      - sqldata

  basket-api:
    image: ${REGISTRY:-eshop}/basket.api:${BRANCH_NAME:-master}
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
    depends_on:
      - basketdata
      - identity-api
      - rabbitmq

  catalog-api:
    image: ${REGISTRY:-eshop}/catalog.api:${BRANCH_NAME:-master}
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    depends_on:
      - sqldata
      - rabbitmq

  ordering-api:
    image: ${REGISTRY:-eshop}/ordering.api:${BRANCH_NAME:-master}
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile
    depends_on:
      - sqldata
      - rabbitmq

  ordering-backgroundtasks:
    image: ${REGISTRY:-eshop}/ordering.backgroundtasks:${BRANCH_NAME:-master}
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.BackgroundTasks/Dockerfile
    depends_on:
      - sqldata
      - rabbitmq

  marketing-api:
    image: ${REGISTRY:-eshop}/marketing.api:${BRANCH_NAME:-master}
    build:
      context: .
      dockerfile: Services/Marketing/Marketing.API/Dockerfile
    depends_on:
      - sqldata
      - nosqldata
      - identity-api
      - rabbitmq

  payment-api:
    image: ${REGISTRY:-eshop}/payment.api:${BRANCH_NAME:-master}
    build:
      context: .
      dockerfile: Services/Payment/Payment.API/Dockerfile
    depends_on:
      - rabbitmq

  locations-api:
    image: ${REGISTRY:-eshop}/locations.api:${BRANCH_NAME:-master}
    build:
      context: .
      dockerfile: Services/Location/Locations.API/Dockerfile
    depends_on:
      - nosqldata
      - rabbitmq

  webhooks-api:
    image: ${REGISTRY:-eshop}/webhooks.api:${BRANCH_NAME:-master}
    build:
      context: .
      dockerfile: Services/Webhooks/Webhooks.API/Dockerfile
    depends_on:
      - sqldata

  mobileshoppingapigw:
    image: ${REGISTRY:-eshop}/mobileshopping.apigw:${BRANCH_NAME:-master}
    build:
      context: .
      dockerfile: ApiGateways/Envoy/Dockerfile

  mobilemarketingapigw:
    image: ${REGISTRY:-eshop}/mobilemarketing.apigw:${BRANCH_NAME:-master}
    build:
      context: .
      dockerfile: ApiGateways/Envoy/Dockerfile

  mobileshoppingagg:
    image: ${REGISTRY:-eshop}/mobileshoppingagg:${BRANCH_NAME:-master}
    build:
      context: .
      dockerfile: ApiGateways/Mobile.Bff.Shopping/aggregator/Dockerfile
    depends_on:
      - nosqldata
      - sqldata
      - identity-api
      - rabbitmq
      - ordering-api
      - marketing-api
      - catalog-api
      - basket-api

  webshoppingagg:
    image: ${REGISTRY:-eshop}/webshoppingagg:${BRANCH_NAME:-master}
    build:
      context: .
      dockerfile: ApiGateways/Web.Bff.Shopping/aggregator/Dockerfile
    depends_on:
      - nosqldata
      - sqldata
      - identity-api
      - rabbitmq
      - ordering-api
      - marketing-api
      - catalog-api
      - basket-api

  ordering-signalrhub:
    image: ${REGISTRY:-eshop}/ordering.signalrhub:${BRANCH_NAME:-master}
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.SignalrHub/Dockerfile
    depends_on:
      - nosqldata
      - sqldata
      - identity-api
      - rabbitmq
      - ordering-api
      - marketing-api
      - catalog-api
      - basket-api

  webstatus:
    image: ${REGISTRY:-eshop}/webstatus:${BRANCH_NAME:-master}
    build:
      context: .
      dockerfile: Web/WebStatus/Dockerfile

  webspa:
    image: ${REGISTRY:-eshop}/webspa:${BRANCH_NAME:-master}
    build:
      context: .
      dockerfile: Web/WebSPA/Dockerfile
      args:
        NODE_IMAGE: ${NODE_IMAGE:-node:10.13}
#    depends_on:
#      - webshoppingagg
#      - webshoppingapigw
#      - webmarketingapigw

  webmvc:
    image: ${REGISTRY:-eshop}/webmvc:${BRANCH_NAME:-master}
    build:
      context: .
      dockerfile: Web/WebMVC/Dockerfile
    depends_on:
      - webshoppingagg
      - webshoppingapigw
      - webmarketingapigw

  webhooks-client:
    image: ${REGISTRY:-eshop}/webhooks.client:${BRANCH_NAME:-master}
    build:
      context: .
      dockerfile: Web/WebhookClient/Dockerfile
    depends_on:
      - webhooks-api

  webshoppingapigw:
    image: ${REGISTRY:-eshop}/webshopping.apigw:${BRANCH_NAME:-master}
    build:
      context: .
      dockerfile: ApiGateways/Envoy/Dockerfile

  webmarketingapigw:
    image: ${REGISTRY:-eshop}/webmarketing.apigw:${BRANCH_NAME:-master}
    build:
      context: .
      dockerfile: ApiGateways/Envoy/Dockerfile
