version: '3.4'

services:
  sql-data-test:
    image: mcr.microsoft.com/mssql/server:2017-latest 

  nosql-data-test:
    image: mongo

  basket-data-test:
    image: redis:alpine

  rabbitmq-test:
    image: rabbitmq:3-management-alpine

  identity-api-test:
    image: ${REGISTRY:-eshop}/identity-api-test:${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Identity/Identity.API/Dockerfile
    depends_on:
      - sql-data-test

  basket-api-functional-test:
    image: mcr.microsoft.com/dotnet/core/sdk:3.1
    working_dir: /app/Services/Basket/Basket.FunctionalTests
    depends_on:
      - basket-data-test
      - identity-api-test
      - rabbitmq-test
    volumes:
      - .:/app
      - ${BUILD_ARTIFACTSTAGINGDIRECTORY:-./tests-results/}:/tests

  basket-api-unit-test:
    image: mcr.microsoft.com/dotnet/core/sdk:3.1
    working_dir: /app/Services/Basket/Basket.UnitTests
    depends_on:
      - basket-data-test
      - identity-api-test
      - rabbitmq-test
    volumes:
      - .:/app
      - ${BUILD_ARTIFACTSTAGINGDIRECTORY:-./tests-results/}:/tests

  catalog-api-functional-test:
    image: mcr.microsoft.com/dotnet/core/sdk:3.1
    working_dir: /app/Services/Catalog/Catalog.FunctionalTests  
    depends_on:
      - sql-data-test
      - rabbitmq-test
    volumes:
      - .:/app
      - ${BUILD_ARTIFACTSTAGINGDIRECTORY:-./tests-results/}:/tests

  catalog-api-unit-test:
    image: mcr.microsoft.com/dotnet/core/sdk:3.1
    working_dir: /app/Services/Catalog/Catalog.UnitTests
    depends_on:
      - sql-data-test
      - rabbitmq-test
    volumes:
      - .:/app
      - ${BUILD_ARTIFACTSTAGINGDIRECTORY:-./tests-results/}:/tests

  ordering-api-functional-test:
    image: mcr.microsoft.com/dotnet/core/sdk:3.1
    working_dir: /app/Services/Ordering/Ordering.FunctionalTests
    depends_on:
      - sql-data-test
      - rabbitmq-test
    volumes:
      - .:/app
      - ${BUILD_ARTIFACTSTAGINGDIRECTORY:-./tests-results/}:/tests

  ordering-api-unit-test:
    image: mcr.microsoft.com/dotnet/core/sdk:3.1
    working_dir: /app/Services/Ordering/Ordering.UnitTests
    depends_on:
      - sql-data-test
      - rabbitmq-test
    volumes:
      - .:/app
      - ${BUILD_ARTIFACTSTAGINGDIRECTORY:-./tests-results/}:/tests

  marketing-api-functional-test:
    image: mcr.microsoft.com/dotnet/core/sdk:3.1
    working_dir: /app/Services/Marketing/Marketing.FunctionalTests
    depends_on:
      - sql-data-test
      - nosql-data-test
      - identity-api-test
      - rabbitmq-test
    volumes:
      - .:/app
      - ${BUILD_ARTIFACTSTAGINGDIRECTORY:-./tests-results/}:/tests

  payment-api-test:
    image: ${REGISTRY:-eshop}/payment-api-test:${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Payment/Payment.API/Dockerfile
    depends_on:
      - rabbitmq-test

  locations-api-functional-test:
    image: mcr.microsoft.com/dotnet/core/sdk:3.1
    working_dir: /app/Services/Location/Locations.FunctionalTests
    depends_on:
      - nosql-data-test
      - rabbitmq-test
    volumes:
      - .:/app
      - ${BUILD_ARTIFACTSTAGINGDIRECTORY:-./tests-results/}:/tests