version: '3.4'

services:
  rabbitmq-test:
    environment:
      RABBITMQ_DEFAULT_USER: ${ESHOP_SERVICE_BUS_USERNAME:-a4pEQTjbY8aKtNBGLKRdbd91Fpp}
      RABBITMQ_DEFAULT_PASS: ${ESHOP_SERVICE_BUS_PASSWORD:-NzCNF1oJ6zQYqIKPM2E46LY$L54OP%sh}
      # RABBITMQ_DEFAULT_VHOST: ${ESHOP_SERVICE_BUS_VHOST}

  basket-api-functional-test:
    entrypoint: sh -c "cd / && chmod 755 ./tests-entrypoint.sh && ./tests-entrypoint.sh"
    volumes:
      - ./tests-entrypoint.sh:/tests-entrypoint.sh
      - ${BUILD_ARTIFACTSTAGINGDIRECTORY:-./tests-results/}:/tests

  basket-api-unit-test:
    entrypoint: sh -c "cd / && chmod 755 ./tests-entrypoint.sh && ./tests-entrypoint.sh"
    volumes:
      - ./tests-entrypoint.sh:/tests-entrypoint.sh
      - ${BUILD_ARTIFACTSTAGINGDIRECTORY:-./tests-results/}:/tests

  catalog-api-functional-test:
    entrypoint: sh -c "cd / && chmod 755 ./tests-entrypoint.sh && ./tests-entrypoint.sh"
    volumes:
      - ./tests-entrypoint.sh:/tests-entrypoint.sh
      - ${BUILD_ARTIFACTSTAGINGDIRECTORY:-./tests-results/}:/tests

  catalog-api-unit-test:
    entrypoint: sh -c "cd / && chmod 755 ./tests-entrypoint.sh && ./tests-entrypoint.sh"
    volumes:
      - ./tests-entrypoint.sh:/tests-entrypoint.sh
      - ${BUILD_ARTIFACTSTAGINGDIRECTORY:-./tests-results/}:/tests

  ordering-api-functional-test:
    entrypoint: sh -c "cd / && chmod 755 ./tests-entrypoint.sh && ./tests-entrypoint.sh"
    volumes:
      - ./tests-entrypoint.sh:/tests-entrypoint.sh
      - ${BUILD_ARTIFACTSTAGINGDIRECTORY:-./tests-results/}:/tests

  ordering-api-unit-test:
    volumes:
      - ./tests-entrypoint.sh:/tests-entrypoint.sh
      - ${BUILD_ARTIFACTSTAGINGDIRECTORY:-./tests-results/}:/tests

    entrypoint: sh -c "cd / && chmod +x -R ./tests-entrypoint.sh && ./tests-entrypoint.sh"
      
  marketing-api-functional-test:
    entrypoint: sh -c "cd / && chmod +x -R ./tests-entrypoint.sh && ./tests-entrypoint.sh"
    volumes:
      - ./tests-entrypoint.sh:/tests-entrypoint.sh
      - ${BUILD_ARTIFACTSTAGINGDIRECTORY:-./tests-results/}:/tests

  locations-api-functional-test:
    entrypoint: sh -c "cd / && chmod 755 ./tests-entrypoint.sh && ./tests-entrypoint.sh"
    volumes:
      - ./tests-entrypoint.sh:/tests-entrypoint.sh
      - ${BUILD_ARTIFACTSTAGINGDIRECTORY:-./tests-results/}:/tests